re-organize ansible stuff into ansible folder + add zsh/vscode roles

diff --git a/bin/dot-bootstrap b/bin/dot-bootstrap
--- a/bin/dot-bootstrap
+++ b/bin/dot-bootstrap
@@ -26,15 +26,24 @@ then
         brew install ansible #@2.9.6
         brew pin ansible
     else
-        echo "On Linux..."
-        sudo apt-add-repository ppa:ansible/ansible -y
-        sudo apt update
-        sudo apt install ansible=2.9.9-1ppa~bionic -V -y
+        release_code=$(lsb_release -c -s)
+        echo "On Linux '$release_code'..."
+        if [[ "$release_code" == "bionic" ]]; then
+            sudo apt-add-repository ppa:ansible/ansible -y
+            sudo apt update
+            sudo apt install ansible=2.9.9-1ppa~bionic -V -y
+        elif [[ "$release_code" == "focal" ]]; then
+            sudo apt update
+            sudo apt install ansible -V -y
+        else
+            echo "ERROR: Unknown linux release code - '$release_code'. Exiting with error"
+            exit 1
+        fi
     fi
 fi
 
-#ansible-playbook -i ~/.dotfiles/hosts ~/.dotfiles/dotfiles.yml --ask-become-pass --tags "$tags"
-ansible-playbook -i ~/.dotfiles/hosts ~/.dotfiles/dotfiles.yml --tags "$tags"
+#ansible-playbook -i ~/.dotfiles/hosts ~/.dotfiles/ansible/dotfiles.yml --ask-become-pass --tags "$tags"
+ansible-playbook -i ~/.dotfiles/ansible/hosts ~/.dotfiles/ansible/dotfiles.yml --tags "$tags"
 
 end=$(date +%s)
 runtime=$((end-start))
